module.exports = [
    {
        binance_bidPrice:0.05,
        binance_askPrice:0.07,
        bitstamp_ask:0.04,
        bitstamp_bid:0.03
    },
    {
        binance_bidPrice:0.05,
        binance_askPrice:0.07,
        bitstamp_ask:0.09,
        bitstamp_bid:0.08
    },
    {
        binance_bidPrice:0.05,
        binance_askPrice:0.07,
        bitstamp_ask:0.09,
        bitstamp_bid:0.08
    },
    {
        binance_bidPrice:0.05,
        binance_askPrice:0.07,
        bitstamp_ask:0.04,
        bitstamp_bid:0.03
    },
    {
        binance_bidPrice:0.05,
        binance_askPrice:0.07,
        bitstamp_ask:0.09,
        bitstamp_bid:0.08
    },
    {
        binance_bidPrice:0.03,
        binance_askPrice:0.04,
        bitstamp_ask:0.02,
        bitstamp_bid:0.01
    },
]